openapi: 3.0.0
info:
  title: Azure Form Recognizer API
  version: 1.0.0
paths:
  /analyze:
    post:
      summary: Analyze a document from URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                formUrl:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /analyzeResults/{resultId}:
    get:
      summary: Get analysis results
      description: Retrieve analysis results from the Document Intelligence service
      parameters:
        - in: path
          name: resultId
          required: true
          description: The ID of the analysis result
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysisResult:
                    type: object
                    description: The analysis result
      security: []
